plugins {
    id("spovishun.kotlin-library")
}

dependencies {
    testImplementation(libs.kotlin.test)
}

// VersionInfo is owned by :common (the module that holds it on the classpath for every consumer,
// including :bot). Generated from the root project version so a release bump stays single-sourced.
// The output file is gitignored — `compileKotlin` regenerates it on every build.
//
// RELEASE_DATE (spovishun-194) comes from :data's `release_notes.json`, which already carries the
// date of every release and is regenerated by the /release flow alongside the version bump. Reading
// it here — a build-script path into a sibling module — is the accepted cost of keeping the runtime
// clean: the alternative was injecting ReleaseNotesRepository into the admin API, which would have
// needed a BotLanguage just to reach a language-independent date. This is the same "build fact
// needed at runtime" that VERSION already is.
val generateVersionInfo by tasks.registering {
    group = "build"
    description = "Generate version info file"
    val target = file("src/main/kotlin/common/util/VersionInfo.kt")
    val botVersion = rootProject.version.toString()
    val releaseNotes = rootProject.file("data/src/main/resources/release_notes.json")
    inputs.property("version", botVersion)
    inputs.file(releaseNotes)
    outputs.file(target)
    doLast {
        // Parsed inline rather than through a build-script helper function: a `doLast` block that
        // calls one captures the script object, which the configuration cache cannot serialize.
        // JsonSlurper ships with the Gradle API, so reading two fields costs no build dependency.
        // `parseText(readText())`, not `parse(File)`: the latter resolves the platform default
        // charset, and release_notes.json is UTF-8 with Cyrillic bodies — the Windows dev machine
        // and the Linux CI runner must not read it differently.
        @Suppress("UNCHECKED_CAST")
        val records = groovy.json.JsonSlurper().parseText(releaseNotes.readText()) as List<Map<String, Any?>>
        // `unknown` is a real path, not a defensive stub: a version bumped in build.gradle.kts before
        // its release_notes.json entry exists must still compile rather than fail the build.
        val releaseDate = records.firstOrNull { it["version"] == botVersion }?.get("date") as? String ?: "unknown"
        // Output must satisfy ktlint (blank line before the function, trailing newline).
        target.writeText(
            """
            package com.ua.astrumon.common.util

            object VersionInfo {
                const val VERSION = "$botVersion"
                const val RELEASE_DATE = "$releaseDate"
                const val BOT_NAME = "Spovishun"

                fun getFullVersion(): String = BOT_NAME + " v" + VERSION
            }
            """.trimIndent() + "\n",
        )
        println("Generated VersionInfo.kt with version: $botVersion ($releaseDate)")
    }
}

// Every task that reads the main source set consumes the generated VersionInfo.kt, so each must
// depend on its producer (Gradle 9 fails the build on an undeclared implicit dependency otherwise).
// `startsWith("detekt")`, not `== "detekt"`: since spovishun-169 the analysis lives in the
// per-source-set tasks (`detektMain`, `detektMainSourceSet`, …) and the aggregate `detekt` task
// itself reads nothing.
tasks
    .matching {
        it.name == "compileKotlin" || it.name.startsWith("detekt") || it.name.startsWith("runKtlint")
    }.configureEach {
        dependsOn(generateVersionInfo)
    }

tasks.test {
    useJUnitPlatform()
}
